# Generated by Django 4.2 on 2026-08-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('cnic', models.CharField(blank=True, max_length=25, null=True)),
                ('role', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photos/')),
                ('cnic_photo', models.ImageField(blank=True, null=True, upload_to='staff/cnic/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('father_cnic', models.CharField(blank=True, max_length=20, null=True)),
                ('student_class', models.CharField(max_length=20)),
                ('roll_no', models.CharField(max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('enrolment_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('monthly_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/photos/')),
                ('form_b_image', models.ImageField(blank=True, null=True, upload_to='students/form_b/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreStudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_no', models.CharField(max_length=50, unique=True)),
                ('fee_month', models.IntegerField()),
                ('fee_year', models.IntegerField()),
                ('tuition_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('transport_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('admission_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('other_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('fine', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('arrears', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Partial', 'Partial')], default='Unpaid', max_length=20)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('EasyPaisa / JazzCash', 'EasyPaisa / JazzCash'), ('Cheque', 'Cheque')], max_length=50, null=True)),
                ('due_date', models.DateField()),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_studentfee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoreTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('cnic', models.CharField(blank=True, max_length=25, null=True)),
                ('subject', models.CharField(max_length=100)),
                ('qualification', models.CharField(blank=True, max_length=150, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='teachers/photos/')),
                ('cnic_photo', models.ImageField(blank=True, null=True, upload_to='teachers/cnic/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'core_teacher',
                'managed': False,
            },
        ),
    ]
